# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
