# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notas_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='id_name',
            field=models.IntegerField(),
        ),
    ]
