# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180716_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='id_name',
            field=models.IntegerField(default=1),
        ),
    ]
