# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_notas_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='id_name',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notas',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
