# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180719_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
