# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180719_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='id_name',
            field=models.IntegerField(),
        ),
    ]
