# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_pass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_password', models.CharField(max_length=30)),
                ('new_password', models.CharField(max_length=30)),
                ('password_confirmed', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
