# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180724_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_pass',
            old_name='last_password',
            new_name='old_password',
        ),
        migrations.RemoveField(
            model_name='change_pass',
            name='password_confirmed',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password_confirmed',
        ),
    ]
