# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180726_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='change_pass',
        ),
    ]
