# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_change_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_pass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_password', models.CharField(max_length=30)),
                ('new_password', models.CharField(max_length=30)),
            ],
        ),
    ]
