# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_change_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='change_pass',
        ),
    ]
